### ISSUE TITLE
virus alert 

### ISSUE THREAD

**Issue by mhmdnopyadly** [openphotogrammetry/meshroomcl#1]
windows defender found virus

**Comment by revisionarian** [comment]
Hi @mhmdnopyadly, thanks for posting this potential virus alert.

However, we have been unable to reproduce this problem on our end. We've tried installing MeshroomCL 0.5.2 on a fresh Windows 10 installation and running every possible Windows Defender virus scan, but no virus threats are reported.

Can you provide more details on what message Windows Defender reported for you? Is there a specific file in the MeshroomCL release that is triggering the virus report? What version of MeshroomCL are you using? Do you see similar problems when you download and scan the original CUDA version of Meshroom ([https://github.com/alicevision/meshroom/releases](https://github.com/alicevision/meshroom/releases))?

**Comment by mhmdnopyadly** [comment]
I'm so sorry, I found that the problem was in another software that was running at the same time.. I'm really sorry... Allow me to delete the comment

**Comment by 3D-360** [comment]
@mhmdnopyadly,

Thank you for determining that the virus was in your system and not our code.  We will probably delete this thread, but it is up to @revisionarian .

Please let us know if you have any issues or thoughts about **meshroomcl**
