### ISSUE TITLE
Possible MPL violation?

### ISSUE THREAD

**Issue by Apollyon094** [openphotogrammetry/meshroomcl#2]
I'm no legal expert, but judging by the following description (https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)):

MPL is a copyleft license that is easy to comply with. You must make the source code for any of your changes available under MPL, but you can combine the MPL software with proprietary code, as long as you keep the MPL code in separate files. Version 2.0 is, by default, compatible with LGPL and GPL version 2 or greater. You can distribute binaries under a proprietary license, as long as you make the source available under MPL.

You may be violating the MPL by not releasing the source code to your changes under the MPL, instead they were not released at all.

Also releasing the source code could mean a lot to the Meshroom developers, since they have been trying to implement OpenCL.

**Comment by revisionarian** [comment]
Thanks for your interest in MeshroomCL, @Apollyon094. We are still developing the software in pre-release mode, and haven't announced its availability yet.

The source code for our changes to Meshroom is available here:

   [https://github.com/openphotogrammetry/meshroomcl](https://github.com/openphotogrammetry/meshroomcl)
