### ISSUE TITLE
OpenCL.dll was not found

### ISSUE THREAD

**Issue by VictorNine** [openphotogrammetry/meshroomcl#29]
Hi when trying to start version 0.8.2 I get an error message saying "The code execution connot proceed because OpenCL.dll was not found. Reinstalling the program may fix this problem."

runnig windows 10

**Comment by revisionarian** [comment]
Hi @VictorNine, yes, MeshroomCL requires that you have the OpenCL.dll file already installed on your system. We do not include it in the MeshroomCL software release, so you'll need to obtain it from another source.

Most users will get the OpenCL.dll file from their Windows 10 installation or when they install their video drivers. Which GPU do you have? I would recommend re-installing your video drivers, or else you can just do a web search for "OpenCL.dll not found" and you will find many pointers to instructions for obtaining and installing  a copy of the OpenCL.dll file on your computer.

**Comment by VictorNine** [comment]
That was easy, issue solved by reinstalling drivers
