### ISSUE TITLE
Can not get this software to run on windows

### ISSUE THREAD

**Issue by Sponsoredby** [openphotogrammetry/meshroomcl#34]
Sorry but I cant get this softwares working getting an error shown below 

<img width="663" alt="2022-02-11 13_33_41-F__Downloads_MeshroomCL-0 8 4-win64_MeshroomCL-0 8 4_Meshroom exe" src="https://user-images.githubusercontent.com/74147554/153604950-25497a0c-cb20-4141-b1ec-93670eb25511.png">

any ideas please ?

**Comment by revisionarian** [comment]
Hi @Sponsoredby, thanks for trying MeshroomCL. We too are confused by the error messages that you are seeing! Could you try downloading the latest MeshroomCL (version 0.8.4), and removing any old versions that you have sitting around?

Is the CUDA version of Meshroom installed anywhere on your computer? Have you installed Python packages separately on your computer, or modified any system-wide Python environment variables? 

Are you running MeshroomCL by double-clicking on the Meshroom.exe icon, or from the command line? What version of Windows do you have?

**Comment by Sponsoredby** [comment]
Thanks, no I wasnt running it from the command line and its working now thanks for getting back to me
