### ISSUE TITLE
Discussion: What will it take the `Instant` NeRF to be imported to work with 'CL'?

### ISSUE THREAD

**Issue by FatCache** [openphotogrammetry/meshroomcl#44]
It is not related to meshroomcl project directly but I figured the best place to ask this question would be here considering folks behind this project managed to port entire Meshroom project to OpenCL!

I recently came across Nvidia's implementation of 'NeRF' and they managed to make it run in an instant mode. As far as I can tell, it is their implementation of https://github.com/bmild/nerf what has been optimized to run on Nvidia GPU - taking advantage of CUDA core/CUDA programming.

My question is, can this be ported to work in 'OpenCL' like it has done with meshroom? Or is there some fundamental piece of the puzzle missing here.

**Comment by revisionarian** [comment]
Hi @FatCache, great question! You are referring to NVIDIA's NGP Instant NeRF (https://github.com/NVlabs/instant-ngp) which is implemented with CUDA, and which also relies on their `tiny-cuda-nn` library that is CUDA-dependent.

Yes, in theory these two software components could be ported from CUDA to OpenCL. Our team does not have any immediate plans to port NeRF to OpenCL, but we have a lot of experience porting computer vision and graphics applications from CUDA to OpenCL, and we are following advances in neural rendering closely. If a good business case presents itself, then we would be interested in pursuing a porting effort.
