### ISSUE TITLE
CLArrayWrapper: clCreateImage: error code=-10

### ISSUE THREAD

**Issue by jujubeesloco** [openphotogrammetry/meshroomcl#7]
OpenCL platform : Intel(R) OpenCL HD Graphics 
OpenCL device   : Intel(R) UHD Graphics 750 
CLArrayWrapper<T>::Allocate() failed in clCreateImage with error code=-10

---------------
I have tried with the Buddha data set..
What is "-10" error?

I can only guess permission, resources, or wrong format.  Or OpenCL is antiquated.

Thank you.

**Comment by revisionarian** [comment]
Hi @jujubeesloco, thanks a lot for reporting your issue with MeshroomCL. The "-10" error that you observed indicates that your OpenCL implementation (the Intel HD graphics driver) does not support the particular OpenCL image format that we used in the old MeshroomCL code.

We released a new version of MeshroomCL today, version 0.7.0, available here:

   https://github.com/openphotogrammetry/meshroomcl/releases

This new version uses a different image format, and will hopefully fix your problem. Please let us know if it does not!
